import { ArchiveEntry, CompletedProject, Lead, Project, Proposal, Task } from "./contracts.js";

export const mockLeads: Lead[] = [
  {
    id: "lead-1",
    name: "Marina Costa",
    company: "Costa Advogados",
    segment: "Advocacia",
    city: "Sao Paulo",
    instagram: "@costa.adv",
    website: "https://costaadv.com.br",
    phone: "+55 11 99222-1001",
    source: "Instagram",
    status: "Proposta enviada",
    proposedValue: 3200,
    notes: "Quer migrar do WordPress para uma stack moderna e premium.",
    nextContact: "2026-03-10",
    tags: ["Quente", "Orcamento enviado"],
    createdAt: "2026-03-05",
  },
  {
    id: "lead-2",
    name: "Felipe Rocha",
    company: "Rocha Odontologia",
    segment: "Odontologia",
    city: "Campinas",
    instagram: "@rochaodonto",
    website: "",
    phone: "+55 19 99111-4400",
    source: "Indicacao",
    status: "Em conversa",
    proposedValue: 1800,
    notes: "Precisa de agenda integrada e landing de conversao com visual premium.",
    nextContact: "2026-03-09",
    tags: ["Quente"],
    createdAt: "2026-03-06",
  },
  {
    id: "lead-5",
    name: "Julia Teles",
    company: "Teles Imoveis",
    segment: "Imobiliaria",
    city: "Goiania",
    instagram: "@telesimoveis",
    website: "https://telesimoveis.com.br",
    phone: "+55 62 98111-2190",
    source: "WhatsApp",
    status: "Fechado",
    proposedValue: 2900,
    notes: "Fechou o pacote institucional com manutencao e esta em fase final de revisao.",
    nextContact: "2026-03-18",
    tags: ["Quente"],
    createdAt: "2026-02-25",
  },
];

export const mockProposals: Proposal[] = [
  {
    id: "proposal-1",
    clientName: "Marina Costa",
    company: "Costa Advogados",
    projectType: "site-institucional",
    extras: ["manutencao-mensal"],
    implementationTotal: 1297,
    monthlyRecurring: 97,
    summary: "Site institucional premium com pages de servicos e captacao via WhatsApp.",
    createdAt: "2026-03-05",
    status: "sent",
    customTitle: "",
    implementationOverride: null,
    recurringOverride: null,
    pricingNotes: "",
  },
  {
    id: "proposal-2",
    clientName: "Julia Teles",
    company: "Teles Imoveis",
    projectType: "site-institucional",
    extras: ["tema-adicional", "entrega-codigo", "manutencao-mensal"],
    implementationTotal: 2600,
    monthlyRecurring: 147,
    summary: "Site institucional com handoff do codigo e contrato mensal de manutencao.",
    createdAt: "2026-02-24",
    status: "accepted",
    customTitle: "Site institucional premium com refinamento comercial",
    implementationOverride: 2600,
    recurringOverride: 147,
    pricingNotes: "Ajuste comercial para escopo maior e onboarding dedicado.",
  },
];

export const mockTasks: Task[] = [
  {
    id: "task-1",
    title: "Enviar follow-up da Costa Advogados",
    description: "Reforcar argumento de autoridade e prazo de entrega premium.",
    priority: "Alta",
    status: "Aberta",
    relatedClient: "Costa Advogados",
    dueDate: "2026-03-09",
    createdAt: "2026-03-07",
  },
  {
    id: "task-2",
    title: "Aprovar hero final da Teles Imoveis",
    description: "Consolidar ajustes finais antes de subir para entrega e onboarding.",
    priority: "Alta",
    status: "Em andamento",
    relatedClient: "Teles Imoveis",
    dueDate: "2026-03-10",
    createdAt: "2026-03-08",
  },
];

export const mockProjects: Project[] = [
  {
    id: "project-1",
    leadId: "lead-5",
    proposalId: "proposal-2",
    clientName: "Julia Teles",
    company: "Teles Imoveis",
    projectType: "site-institucional",
    status: "Revisao",
    implementationTotal: 2600,
    monthlyRecurring: 147,
    dueDate: "2026-03-14",
    nextMilestone: "2026-03-10",
    maintenanceActive: true,
    notes: "Aguardando validacao final das paginas internas e disparo do onboarding.",
    deliverySummary: "Site institucional premium com prova social, CTA para WhatsApp e base de manutencao.",
    createdAt: "2026-02-26",
  },
];

export const mockArchive: ArchiveEntry[] = [
  {
    id: "archive-1",
    leadId: "lead-archive-1",
    name: "Camila Prado",
    company: "Prado Clinica Integrada",
    statusAtArchive: "Perdido",
    reason: "Preco fora do contexto",
    notes: "Entrou no radar, mas o momento financeiro travou a decisao.",
    archivedAt: "2026-03-02",
  },
];

export const mockCompletedProjects: CompletedProject[] = [
  {
    id: "completed-1",
    projectId: "project-old-1",
    clientName: "Arthur Lima",
    company: "Lima Odontologia Estetica",
    projectType: "landing-essencial",
    implementationTotal: 1400,
    monthlyRecurring: 97,
    deliveredAt: "2026-02-12",
    notes: "Entrega feita com onboarding por WhatsApp e checklist final enviado.",
    deliverySummary: "Landing premium para implantes com CTA, prova social e campanha principal publicada.",
  },
];
